### ISSUE TITLE
Colors were copied 😒

### ISSUE THREAD

**Issue by KyleSmith0905** [Devs-Us/EpicColors#5]
Some of the colors are copied from another color mod. I selected a few colors to compare, but of course, more exists from the same source. Their color mod existed before us.

| Hex| Devs-Us|  Source|
|---|---|---|
| #637218| [Olive](https://github.com/Devs-Us/EpicColors/blob/master/EpicColors/EpicColors/EpicColors.cs#L59)| [Olive](https://github.com/MoltenMods/Rainbow/blob/269b62dc80e583b8c73a6d9b63e561ede987dd65/Rainbow/Patches/ColorSelectionPatches.cs#L23)|
| #c992e0| [Lavender](https://github.com/Devs-Us/EpicColors/blob/master/EpicColors/EpicColors/EpicColors.cs#L50)| [Lavender](https://github.com/MoltenMods/Rainbow/blob/269b62dc80e583b8c73a6d9b63e561ede987dd65/Rainbow/Patches/ColorSelectionPatches.cs#L35)|

If these were actually a coincident (maybe both of you were using the same source), than I apologize.

**Comment by disabledworx** [comment]
This was actually coincidence.

**Comment by Matthew-MBG** [comment]
Please don't. Olive is a color that was voted to not be in the game, as seen [here](https://among-us.fandom.com/wiki/Olive).

**Comment by KyleSmith0905** [comment]
### Closing
This is address in #6. Any discussion will be moved there.
